version: '3.9'

services:
    mlflow:
        build: ./mlflow
        container_name: mlflow
        ports:
            - '5000:5000'
        environment:
            - BACKEND_STORE_URI=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}_mlflow
            - ARTIFACT_ROOT=s3://mlflow/
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
            - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
        depends_on: [mysql, minio]
        networks: [risknet]

    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
            - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data
        networks: [risknet]

    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./db/init:/docker-entrypoint-initdb.d
        networks: [risknet]

    training:
        build: ./training
        container_name: training
        ports:
            - '8002:8000'
        environment:
            - MLFLOW_TRACKING_URI=http://mlflow:5000
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
            - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
            - AWS_S3_VERIFY_SSL=false
            - DATABASE_URI={DB_URI}
            - MLFLOW_EXPERIMENT_NAME=LSTM_Financial_Forecast
        depends_on: [mysql, mlflow, minio]
        networks: [risknet]

    inference:
        build: ./inference
        container_name: inference
        ports:
            - '8001:8000'
        environment:
            - MLFLOW_TRACKING_URI=http://mlflow:5000
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
            - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
            - AWS_S3_VERIFY_SSL=false
            - DATABASE_URI={DB_URI}
            - MODEL_BUCKET={MODEL_BUCKET}
            - MODEL_ARTIFACT_PATH={MODEL_ARTIFACT_PATH}
        depends_on: [mysql, mlflow, minio]
        networks: [risknet]

    be:
        build: ./be
        container_name: be
        ports:
            - '8000:8000'
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_USER=${MYSQL_USER}
            - DB_PASSWORD=${MYSQL_PASSWORD}
            - DB_NAME=${MYSQL_DATABASE}
            - INFERENCE_URL=http://inference:8000
        depends_on: [mysql, inference, training]
        networks: [risknet]

networks:
    risknet:

volumes:
    mysql_data:
    minio_data:
