# tunnel: <TUNNEL_ID>            # 토큰 방식이면 생략 가능
# credentials-file: /etc/cloudflared/<TUNNEL_ID>.json

ingress:
    - hostname: api.example.com
      service: http://be:8000
    - hostname: mlflow.example.com
      service: http://mlflow:5000
    - hostname: minio.example.com
      service: http://minio:9001 # 콘솔 UI
    - hostname: s3.example.com
      service: http://minio:9000 # S3 API (Access 정책으로 보호 권장)
    - service: http_status:404
